# Generated by Django 4.0.10 on 2023-03-23 12:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path)),
                ('slug', models.SlugField()),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_file', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
