# Generated by Django 4.0.10 on 2023-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
