# Generated by Django 4.0.10 on 2023-03-30 08:55

from django.db import migrations, models
import djgumroad.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_customer_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to=djgumroad.users.models.create_user_image_profile_path),
        ),
    ]
